# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from constants import globalConstants

class TestAtozcheck():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_atozcheck(self):
    self.driver.get(globalConstants.URL)
    self.driver.set_window_size(1080, 1032)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
    WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#inventory_container #inventory_container")))
    dropdown = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"product_sort_container\"]")
    dropdown.find_element(By.XPATH, "//option[. = 'Price (low to high)']").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"product_sort_container\"]").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"product_sort_container\"]")
    dropdown.find_element(By.XPATH, "//option[. = 'Name (A to Z)']").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"product_sort_container\"]").click()
    urun_listesi = self.driver.find_elements(By.CLASS_NAME,"inventory_item_name")
    urunler_adi = []
    for urun in urun_listesi:
      urunler_adi.append(urun.text)
    assert globalConstants.sorted_product_list == urunler_adi
